// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TZ643P : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.tZ643P_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.tZ643P_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleLaser
        {
            get
            {
                return SteamVR_Actions.tZ643P_ToggleLaser;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.tZ643P_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.tZ643P_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.tZ643P_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.tZ643P_Haptic;
            }
        }
    }
}
